apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: q021d5i3v-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-ff79f72ee8.8oy7.p3.openshiftapps.com/rhtap/rhtap-qe:84e4598275223b65793a090899e6692e50acaeb0@sha256:4761cbf833027fdfd3dcbf3899f02e7957a92e34f6c4ee0b25c9250be02fcefa
          name: container-image
